language: python
python:
    - '3.5'
sudo: false
cache:
    directories:
        - "$HOME/.cache/pip"
        - "node/node_modules"
services:
    - postgresql
install:
    - pip install -U pip flake8 -r requirements.txt
    - nvm install 6
    - cd node; npm install eslint; cd ..
before_script:
    - cp web3/settings/secret.sample web3/settings/secret.py
    - psql -U postgres -c "create database web3"
script:
    - flake8 --max-line-length=200 .
    - ./node/node_modules/eslint/bin/eslint.js node/*.js
    - ./node/node_modules/eslint/bin/eslint.js web3/static/js/sites/*.js
    - ./manage.py migrate
