language: python
python:
    - '3.5'
sudo: required
cache:
    directories:
        - "$HOME/.cache/pip"
        - "node/node_modules"
services:
    - postgresql
before_install:
    - sudo apt-get -y update
install:
    - sudo apt-get -y install libvirt-dev
    - pip install -U pip flake8 -r requirements.txt
    - nvm install 6
    - cd node; npm install; cd ..
before_script:
    - cp web3/settings/secret.sample web3/settings/secret.py
    - psql -U postgres -c "create database web3"
script:
    - flake8 --max-line-length=200 --exclude=node_modules,venv .
    - ./node/node_modules/eslint/bin/eslint.js --env node node/
    - ./node/node_modules/eslint/bin/eslint.js --env browser web3/static/js/
    - ./manage.py migrate
    - ./manage.py test
