# Dependabot configuration file
# Configures when automatic dependency PRs are created
version: 1
update_configs:
  - package_manager: "python"
    directory: "/"
    update_schedule: "weekly"

    default_reviewers:
      - "theo-o"
    default_labels:
      - "dependencies"
    target_branch: "dev"
    allowed_updates:
      - match:
          update_type: "security"
